#!/usr/bin/env python3
"""Build the static GitHub preview. Production indexing requires --production."""
from pathlib import Path
from html import escape as e
import argparse
import json
from hashlib import sha256
from content import HUBS, PLATFORMS, MODEL, POSITION, HERO, INTRO, PROGRAM, ARCHITECTURE

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = Path(__file__).parent / 'templates'
PRODUCTION = argparse.ArgumentParser()
PRODUCTION.add_argument('--production', action='store_true')
PRODUCTION.add_argument('--contact-endpoint', default='')
args = PRODUCTION.parse_args()
production = args.production
contact_endpoint = args.contact_endpoint
if contact_endpoint and (production or contact_endpoint != 'https://forms-preview.gentech.ae/contact.php'):
    PRODUCTION.error('Only the approved test endpoint is allowed, and only in preview builds.')
PAGES = []

def link(url, text, cls='g-text-link'):
    return f'<a class="{cls}" href="{e(url)}">{e(text)} <span aria-hidden="true">↗</span></a>'

def section(id, eyebrow, title, content, desc='', cls=''):
    return f'<section id="{id}" class="g-section {cls}"><div class="g-container"><div class="g-section-heading"><div><span class="g-eyebrow">{e(eyebrow)}</span><h2>{title}</h2></div>{f"<p>{e(desc)}</p>" if desc else ""}</div>{content}</div></section>'

def intro(eyebrow, title, desc):
    return f'<section class="g-page-intro"><div class="g-container"><span class="g-eyebrow">{e(eyebrow)}</span><h1>{e(title)}</h1><p class="g-lead">{e(desc)}</p></div></section>'

def hubcards():
    return '<div class="g-grid g-three">' + ''.join(f'<article class="g-hub"><span class="g-eyebrow">0{i+1} / {e(h["country"])}</span><h3>{e(h["city"])}</h3><p class="g-hub-role">{e(h["role"])}</p><strong>{e(h["name"])}</strong><address>{e(h["address"])}</address>{link("group-"+h["key"]+".html", "Explore this platform")}</article>' for i,h in enumerate(HUBS)) + '</div>'

def models():
    return '<div class="g-grid g-four">' + ''.join(f'<article class="g-model"><span class="g-index">0{i+1}</span><h3>{a}</h3><strong>{b}</strong><p>{c}</p></article>' for i,(a,b,c) in enumerate(MODEL)) + '</div>'

def platformcards():
    return '<div class="g-grid g-three g-platforms">' + ''.join(f'<a class="g-platform" href="solutions-{p["key"]}.html"><span class="g-index">0{i+1}<span aria-hidden="true">↗</span></span><h3>{e(p["title"])}</h3><p>{e(p["description"])}</p></a>' for i,p in enumerate(PLATFORMS)) + '</div>'

def metrics():
    return '<div class="g-metrics">' + ''.join(f'<div><strong>{a}</strong><span>{b}</span></div>' for a,b in [('3','Global Operating Hubs'),('6','Strategic Business Platforms'),('10-Year','National Mobility Program'),('500,000','Vehicle Program Scope')]) + '</div>'

def project():
    return f'<article class="g-feature"><div class="g-feature-art"><img src="assets/images/mobility_banner.webp" alt="Illustrative connected transport and mobility technology" loading="lazy"><span>SOUTH AFRICA PROGRAM · ILLUSTRATIVE IMAGE</span></div><div class="g-feature-copy"><span class="g-eyebrow">10-YEAR CONTRACTUAL PROGRAM</span><h3>National Digital Transportation &amp; Payments Program</h3><p>{e(PROGRAM)}</p><div class="g-inline-facts"><span><b>500,000</b>Vehicle program scope</span><span><b>65 Million</b>Potential population reach</span></div><p class="g-caption">Program scope and potential reach are not measures of active vehicles, daily passengers or live users.</p>{link("africa-national-mobility-program.html", "Explore the program")}</div></article>'

def chairman_block():
    return f'<div class="g-vision"><span class="g-quote-mark" aria-hidden="true">“</span><div><blockquote>At Gentech Group, we believe the true measure of technology lies in the trust, convenience, and enduring economic opportunity it creates in people’s daily lives.</blockquote><div class="g-attribution"><p class="g-attribution-name" translate="no"><strong>Mustafa Sertkaya</strong></p><p class="g-attribution-role">Chairman, Gentech Group</p></div><p class="g-caption">Strategic Leadership • Payment Technologies • International Infrastructure</p>{link("chairman.html", "Read the Chairman’s message")}</div></div>'

def contact_cta():
    return '<div class="g-contact-cta"><div><span class="g-eyebrow">LET’S START A CONVERSATION</span><h2>Build the next<br><em>connection.</em></h2><p>Discuss a project, a partnership or a technology requirement with Gentech Group.</p></div>'+link('contact.html','Contact the group','g-button')+'</div>'

def header():
    group = '<a href="about.html">About the group</a>' + ''.join(f'<a href="group-{h["key"]}.html">{e(h["city"])} · {e(h["country"])}</a>' for h in HUBS) + '<a href="chairman.html">Chairman’s message</a>'
    platforms = ''.join(f'<a href="solutions-{p["key"]}.html">{e(p["title"])}</a>' for p in PLATFORMS)
    return f'<a class="g-skip" href="#main">Skip to content</a><header class="g-header"><div class="g-nav-wrap"><a class="g-brand" href="index.html" aria-label="Gentech Group home"><span class="g-brand-symbol" aria-hidden="true">G</span><span>GENTECH <b>GROUP</b></span></a><button class="g-menu-toggle" aria-controls="mainNav" aria-expanded="false" type="button">Menu <span aria-hidden="true">☰</span></button><nav id="mainNav" class="g-nav" aria-label="Main navigation"><a href="index.html">Home</a><details><summary>Group</summary><div class="g-dropdown">{group}</div></details><details><summary>Business Platforms</summary><div class="g-dropdown g-wide">{platforms}</div></details><a href="projects.html">Projects</a><a href="news.html">News</a><a class="g-nav-contact" href="contact.html">Contact <span aria-hidden="true">↗</span></a></nav></div></header>'

def footer():
    return '<footer class="g-footer"><div class="g-container"><div class="g-footer-main"><div><a class="g-brand" href="index.html">GENTECH <b>GROUP</b></a><p>Capital • Technology • Infrastructure • Operations</p></div><div class="g-footer-links"><a href="about.html">The group</a><a href="index.html#business-platforms">Business Platforms</a><a href="contact.html">Global offices</a><a href="mailto:info@gentech.ae">info@gentech.ae</a></div></div><div class="g-footer-bottom"><span>© 2026 Gentech Group</span><span>Toronto · Ras Al Khaimah · Johannesburg</span><nav aria-label="Legal"><a href="legal.html">Legal</a><a href="privacy.html">Privacy</a><a href="terms.html">Terms</a><a href="compliance.html">Compliance</a></nav></div></div></footer>'

def page(file, title, desc, body, studio=False):
    canonical = 'https://gentech.ae/' + ('' if file == 'index.html' else file)
    schema = dict(**{'@context':'https://schema.org','@type':'Organization'},name='Gentech Group',url='https://gentech.ae/',email='info@gentech.ae',location=[{'@type':'Place','name':h['name'],'address':h['address']} for h in HUBS])
    def versioned_script(path):
        version = sha256((ROOT/path).read_bytes()).hexdigest()[:12]
        return f'<script defer src="{path}?v={version}"></script>'
    scripts = versioned_script('assets/js/holding.js')
    if file == 'contact.html' and contact_endpoint:
        scripts += versioned_script('assets/js/enquiry.js')
    if studio:
        scripts += '<script defer src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script><script defer src="assets/js/scene3d.js"></script>'
    html = f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} | Gentech Group</title><meta name="description" content="{e(desc)}"><meta name="robots" content="{"index,follow" if production else "noindex,follow"}"><link rel="canonical" href="{canonical}"><meta property="og:type" content="website"><meta property="og:site_name" content="Gentech Group"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{canonical}"><meta name="theme-color" content="#faf5ef"><link rel="icon" href="assets/images/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,500;0,600;1,500&display=swap" rel="stylesheet">{"<link rel=\"stylesheet\" href=\"assets/css/style.css\">" if studio else ""}<link rel="stylesheet" href="assets/css/holding.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script>{scripts}</head><body class="g-site">{header()}<main id="main">{body}</main>{footer()}</body></html>\n'
    css_version = sha256((ROOT/'assets/css/holding.css').read_bytes()).hexdigest()[:12]
    html = html.replace('href="assets/css/holding.css"', f'href="assets/css/holding.css?v={css_version}"')
    (ROOT/file).write_text(html)
    PAGES.append(file)

network = (TEMPLATES/'network.svg').read_text()
home = f'<section class="g-opening" id="opening"><div class="g-container"><div class="g-hero-grid"><div><span class="g-eyebrow">CAPITAL · TECHNOLOGY · INFRASTRUCTURE · OPERATIONS</span><h1>{HERO}</h1><p class="g-lead">{INTRO}</p><div class="g-actions">{link("index.html#business-platforms","Explore our platforms","g-button")}{link("africa-national-mobility-program.html","Our flagship program")}</div></div><div class="g-network">{network}<p class="g-caption">Three operating hubs. One integrated approach.<br>Conceptual network illustration.</p></div></div>{metrics()}</div></section>'
home += section('what-we-do','OUR OPERATING MODEL','What We Do',models(),POSITION)
home += section('business-platforms','SIX CONNECTED PLATFORMS','Business Platforms',platformcards(),'An integrated international technology and investment group','g-tinted')
home += section('featured-projects','STRATEGY INTO DELIVERY','Featured Projects',project())
home += section('global-presence','THREE GLOBAL OPERATING HUBS','Global Presence',hubcards(),'Distinct roles across capital coordination, technology integration and local implementation.','g-tinted')
home += section('chairmans-vision','LONG-TERM PERSPECTIVE','Chairman’s Vision',chairman_block())
portfolio = '<div class="g-grid g-three">' + ''.join(f'<a class="g-portfolio" href="{url}"><div><img src="assets/images/{img}" alt="{alt}" loading="lazy"></div><h3>{title}</h3><p>{desc}</p><span class="g-text-link">Explore technology ↗</span></a>' for url,img,alt,title,desc in [('solutions-cards.html','metalcard.webp','Illustrative card and secure payment product designs','Cards &amp; Secure Payment Products','Design, personalisation, production management and international supply.'),('solutions-payments.html','pos.webp','Illustrative payment terminal','Secure Payment Technologies','Product selection and integration with licensed payment partners.'),('solutions-telecom.html','supersim.webp','Illustrative connected-device SIM products','Connected Devices','Communications products for connected infrastructure and mobility.')]) + '</div>'
home += section('technology-portfolio','PRODUCT EXPERTISE WITHIN THE GROUP','Technology Portfolio',portfolio,cls='g-tinted')
home += section('partnerships','A COORDINATED APPROACH','Partnerships','<div class="g-partnership"><h3>SANTACO, acting through TaxiChoice</h3><p>'+e(PROGRAM)+'</p><p>Technology implementation is coordinated around project requirements. Banking and regulated payment services require appropriately licensed partners.</p>'+link('contact.html?dept=partnerships','Discuss a partnership')+'</div>')
home += section('news','GROUP INSIGHTS','News','<article class="g-news-row"><span class="g-eyebrow">PROGRAM OVERVIEW</span><div><h3>Inside the national mobility program</h3><p>Contractual scope, operating roles and the distinction between architecture and deployment.</p></div>'+link('africa-national-mobility-program.html','Read overview')+'</article>',cls='g-tinted')
home += '<section id="contact" class="g-section"><div class="g-container">'+contact_cta()+'</div></section>'
page('index.html',HERO,INTRO,home)

page('about.html','An integrated international technology and investment group',POSITION,intro('THE GROUP','Capital. Technology. Infrastructure. Operations.',POSITION)+section('model','OUR APPROACH','From development to operations',models())+section('structure','INTERNATIONAL PLATFORM','Three hubs. Complementary roles.',hubcards(),'Corporate roles described here do not imply an unverified parent-subsidiary ownership structure.','g-tinted')+section('platforms','OUR BUSINESS','Six strategic platforms',platformcards()))

for h in HUBS:
    body = intro(h['country'],h['name'],h['description'])
    body += section('role','OPERATING ROLE',h['role'],f'<div class="g-split"><div><p class="g-lead">{e(h["description"])}</p><p>Part of Gentech Group’s coordinated international approach to capital, technology, infrastructure and operations.</p>{link("contact.html?dept="+h["key"],"Contact this office")}</div><div class="g-address-panel"><span class="g-eyebrow">OFFICIAL CORPORATE ADDRESS</span><h3>{e(h["city"])}</h3><strong>{e(h["name"])}</strong><address>{e(h["address"])}</address><a href="mailto:info@gentech.ae">info@gentech.ae</a></div></div>')
    if h['key']=='africa': body += section('program','PROGRAM IMPLEMENTATION','National mobility program',project())
    body += section('global','GROUP CONNECTIONS','Global Presence',hubcards(),cls='g-tinted')
    page('group-'+h['key']+'.html',h['city']+' operating hub',h['description'],body)

for p in PLATFORMS:
    title = 'Cards & Secure Payment Products' if p['key']=='cards' else p['title']
    body = intro('BUSINESS PLATFORM / '+str(PLATFORMS.index(p)+1).zfill(2),title,p['description'])
    if p['key']=='cards': body += (TEMPLATES/'card-studio.html').read_text()
    items = '<div class="g-grid g-two">'+''.join(f'<article class="g-capability"><span class="g-index">0{i+1}</span><h3>{e(v)}</h3><p>Coordinated around the product, project requirements and relevant specialist partners.</p></article>' for i,v in enumerate(p['items']))+'</div>'
    body += section('capabilities','PLATFORM FOCUS','Expertise and delivery scope',items,cls='g-tinted')
    if p['key']=='cards':
        body += section('product-families','MATERIALS & SPECIFICATIONS','Designed around the application.','<div class="g-grid g-three"><article class="g-card"><h3>Metal &amp; titanium</h3><p>Material, weight, finish, engraving and personalisation options are specified for each product.</p></article><article class="g-card"><h3>Ceramic &amp; composite</h3><p>Surface finish, colour and construction are selected together with the production partner.</p></article><article class="g-card"><h3>Contactless &amp; wearable</h3><p>Chip, antenna, form factor and payment-system compatibility depend on the selected product and issuer requirements.</p></article></div><div class="g-note"><strong>Specification and certification scope</strong><p>Final dimensions, chip options, durability, compatibility and lead times are confirmed through product-specific documentation and sample approval. Any third-party certification must be assessed for its holder, product scope and validity; no group-wide certification is claimed here.</p></div>'+link('contact.html?dept=cards','Request specifications or a sample','g-button'))
    elif p['key']=='mobility': body += section('program','FEATURED PROJECT','National mobility program',project())
    elif p['key'] in ['payments','infrastructure','telecom']:
        body += section('architecture','DESIGN & IMPLEMENTATION','Architecture with a clear scope.',f'<div class="g-note"><p>{e(ARCHITECTURE)}</p><p>Capability descriptions are design and integration scopes, not confirmation that every component is deployed or available in every market.</p></div>')
    body += '<section class="g-section"><div class="g-container">'+contact_cta()+'</div></section>'
    page('solutions-'+p['key']+'.html',title,p['description'],body,p['key']=='cards')

body = intro('SOUTH AFRICA / 10-YEAR CONTRACTUAL PROGRAM','National Digital Transportation & Payments Program',PROGRAM)
body += section('scope','CONTRACTUAL PROGRAM','A defined national scope.',metrics()+'<p class="g-reach">Potential Population Reach: 65 Million</p><p class="g-caption">The 500,000-vehicle figure is program scope. Potential population reach is not daily ridership, active accounts or a claim of completed deployment.</p>')
body += section('roles','AGREEMENT & IMPLEMENTATION','Clear roles. Accurate language.',f'<div class="g-split"><article><h3>Contractual foundation</h3><p>{e(PROGRAM)}</p><p>The program is established under an existing agreement. Its contractual status does not represent a grant of government authority.</p></article><article><h3>Johannesburg implementation</h3><p>{e(HUBS[2]["description"])}</p><p>This operating description does not assert that the company is the direct signatory or an exclusive executor.</p></article></div>',cls='g-tinted')
body += section('architecture','PROGRAM DESIGN','Connected transport. Integrated payments.',f'<p class="g-lead">{e(ARCHITECTURE)}</p><div class="g-grid g-three">'+''.join(f'<article class="g-card"><h3>{a}</h3><p>{b}</p></article>' for a,b in [('Passenger access','Designed to support contactless and QR-based access, subject to product selection and integration.'),('Vehicle connectivity','Designed to support connected validators, terminal communications and operational reporting.'),('Payment coordination','Designed to support clearing, reconciliation, settlement and payout workflows with licensed banking and payment partners.')])+'</div><div class="g-note"><strong>Architecture is not deployment status.</strong><p>The capabilities above describe intended system support. Implementation, service availability and regulated functions depend on agreed phases, technical validation and relevant partner arrangements.</p></div>')
body += section('contact','PROJECT ENQUIRIES','Discuss the program.',link('contact.html?dept=mobility','Contact the mobility team','g-button'))
page('africa-national-mobility-program.html','National Mobility Program · South Africa',PROGRAM,body)
page('projects.html','Projects & infrastructure programs','Explore Gentech Group’s contractually established national mobility program and integrated project approach.',intro('PROJECTS','Long-term programs. Integrated delivery.','Bringing project development, capital coordination, technology and operations together.')+section('featured','PROGRAM FOCUS','National mobility & payments',project())+section('approach','HOW WE WORK','From scope to implementation',models()))

body=intro('LEADERSHIP','Mustafa Sertkaya','Chairman, Gentech Group')
body+=section('vision','CHAIRMAN’S MESSAGE','Technology with enduring purpose.',chairman_block())
body+=section('message','A LONG-TERM PERSPECTIVE','Connecting ambition with delivery.','<div class="g-prose"><p>Our focus is to bring capital, technology, infrastructure and operations together around projects that respond to practical needs. Across Toronto, Ras Al Khaimah and Johannesburg, the group’s platforms contribute distinct expertise to this shared approach.</p><p>The national digital transportation and payments program in South Africa reflects that long-term perspective. It is a contractually established 10-year program under Gentech’s agreement with SANTACO acting through TaxiChoice, with a 500,000-vehicle program scope.</p><p>Potential Population Reach: 65 Million. This figure describes potential reach, not daily passengers or active users. The program’s technical architecture is designed to support its capabilities with appropriately licensed banking, payment and technology partners.</p><p>Responsible progress means being clear about our role, the scope of each project and the work required to deliver it.</p></div>',cls='g-tinted')
body+=section('turkish','TÜRKÇE','Uzun vadeli değer için teknoloji.','<div class="g-prose" lang="tr"><p>Gentech olarak teknolojinin gerçek değerinin, insanların günlük hayatında oluşturduğu güven, kolaylık ve yeni fırsatlarla ölçüldüğüne inanıyoruz.</p><p>Sermaye, teknoloji, altyapı ve operasyon kabiliyetlerini aynı proje yaklaşımında buluşturuyoruz. Toronto, Ras Al Khaimah ve Johannesburg platformlarımız bu yapıya farklı uzmanlıklarla katkı sağlıyor.</p><p>Güney Afrika’daki ulusal dijital ulaşım ve ödeme programımız, SANTACO’nun TaxiChoice aracılığıyla hareket ettiği anlaşmamıza dayanan 10 yıllık bir program. 500.000 araç program kapsamını, 65 milyon kişi ise potansiyel nüfus erişimini ifade ediyor; günlük yolcu veya aktif kullanıcı sayısını değil.</p><p>Teknik mimari, ilgili lisanslara sahip bankacılık, ödeme ve teknoloji ortaklarıyla uygulanacak kabiliyetleri desteklemek üzere tasarlanıyor.</p></div>')
page('chairman.html','Mustafa Sertkaya · Chairman','Strategic Leadership • Payment Technologies • International Infrastructure',body)
page('news.html','News & group insights','Program context and insights from Gentech Group.',intro('NEWS & INSIGHTS','A closer look at the group.','Explore the structure, technology scope and long-term programs behind Gentech Group.')+section('insights','GROUP READING','Program & platform insights','<div class="g-grid g-three"><article class="g-card"><span class="g-eyebrow">PROGRAM OVERVIEW</span><h3>National mobility in South Africa</h3><p>Understand the contractual program and the distinction between scope and deployment.</p>'+link('africa-national-mobility-program.html','Read overview')+'</article><article class="g-card"><span class="g-eyebrow">GROUP OVERVIEW</span><h3>Three hubs. Six platforms.</h3><p>How capital, technology and local implementation fit within the group.</p>'+link('about.html','Explore the group')+'</article><article class="g-card"><span class="g-eyebrow">TECHNOLOGY PORTFOLIO</span><h3>Cards &amp; secure payment products</h3><p>Explore product design, material directions and personalisation.</p>'+link('solutions-cards.html','Explore the portfolio')+'</article></div>'))

options=[('general','General enquiry'),('capital','Capital & strategic investments'),('infrastructure','Infrastructure development'),('mobility','National mobility program'),('payments','Payment technologies'),('telecom','Connected devices'),('cards','Cards & samples'),('partnerships','Partnerships'),('canada','Toronto office'),('uae','Ras Al Khaimah office'),('africa','Johannesburg office')]
form='<div class="g-split g-contact-layout"><div><h3>Tell us what you have in mind.</h3><p>For this preview, the enquiry tool prepares an email to <a href="mailto:info@gentech.ae">info@gentech.ae</a>. You review and send it in your email application.</p><p>No message is submitted to a server or CRM here, and no automatic acknowledgement is issued. The selected enquiry topic is included in the subject for the receiving team.</p><p>Please do not include card numbers, passwords or confidential documents.</p></div><form id="enquiryForm"><div class="g-form-row"><div><label for="fullName">Full name</label><input id="fullName" name="name" autocomplete="name" maxlength="100" required></div><div><label for="email">Email address</label><input id="email" name="email" type="email" autocomplete="email" maxlength="180" required></div></div><label for="company">Company <span>(optional)</span></label><input id="company" name="company" autocomplete="organization" maxlength="160"><label for="department">Enquiry topic</label><select id="department" name="department">'+''.join(f'<option value="{v}">{l}</option>' for v,l in options)+'</select><label for="message">How can we help?</label><textarea id="message" name="message" rows="5" minlength="10" maxlength="2500" required></textarea><label class="g-consent"><input type="checkbox" name="consent" id="consent" required><span>I have read the <a href="privacy.html">privacy notice</a> and agree to use these details for responding to my enquiry.</span></label><button class="g-button" type="submit">Prepare email draft <span aria-hidden="true">↗</span></button><div id="enquiryResult" class="g-form-result" role="status" hidden><p>Your draft is ready. Nothing has been sent or recorded in a CRM.</p><a class="g-button" id="emailDraft" href="mailto:info@gentech.ae">Open email application ↗</a><p>No email application? Copy the draft below and send it to info@gentech.ae.</p><textarea id="draftText" aria-label="Prepared email text" rows="8" readonly></textarea></div><noscript><p>The draft tool needs JavaScript. You can email info@gentech.ae directly.</p></noscript></form></div>'
if contact_endpoint:
    form = (TEMPLATES/'contact-form.html').read_text().replace('{{ENDPOINT}}', e(contact_endpoint)).replace('{{OPTIONS}}', ''.join(f'<option value="{v}">{e(l)}</option>' for v,l in options))
page('contact.html','Contact & global offices','Contact Gentech Group at info@gentech.ae. Official corporate addresses in Toronto, Ras Al Khaimah and Johannesburg.',intro('CONTACT','Let’s build the next connection.','Project development, investment coordination, technology integration or product enquiries — start a conversation with the group.')+section('enquiry','START A CONVERSATION','Your enquiry',form)+section('offices','VERIFIED CORPORATE DETAILS','Global offices',hubcards(),cls='g-tinted'))

legal={
'legal.html':('Legal & corporate information','<h2>Group identity and corporate roles</h2><p>Gentech Group is the group brand used on this website. The corporate names, addresses and stated operating roles below identify the relevant platforms. This presentation does not establish or represent an unverified shareholding hierarchy.</p>'+''.join(f'<h3>{e(h["name"])}</h3><address>{e(h["address"])}</address><p>{e(h["description"])}</p>' for h in HUBS)+'<h2>Program and capability statements</h2><p>'+e(PROGRAM)+'</p><p>Program scope is distinct from completed deployment. Descriptions of system architecture do not confirm live operations, regulatory approval or group-wide technical certification.</p>'),
'privacy.html':('Privacy notice','<h2>Enquiries on this preview</h2><p>The enquiry tool processes the name, email, company, topic and message you enter locally in your browser to prepare an email draft. It does not submit these fields to a website backend or CRM, and it does not store the draft in browser storage. You choose whether to open your email application and send the message.</p><h2>When you send an email</h2><p>Your chosen email service handles transmission. Information sent to info@gentech.ae can be used to review and respond to your enquiry and coordinate with the relevant group team. Do not send sensitive payment data or credentials. Contact info@gentech.ae for questions about your information or requests concerning an enquiry.</p><h2>Hosting and external resources</h2><p>The preview is hosted on GitHub Pages. Normal hosting requests can expose technical connection information, including an IP address, to the hosting provider. Fonts load from Google Fonts; the interactive card page loads its 3D library from Cloudflare’s CDN. These providers receive connection information when those resources load.</p><h2>Tracking and storage</h2><p>This version does not intentionally set analytics, advertising or CRM cookies, and the enquiry tool does not use browser storage. External providers and your email application operate under their own privacy terms.</p>'),
'terms.html':('Website terms','<h2>Information and enquiries</h2><p>This website provides general information about Gentech Group, its corporate platforms, programs and technology portfolio. Product visualisations are illustrative and do not constitute a binding specification, offer or availability commitment.</p><h2>Products and projects</h2><p>Commercial terms, final technical specifications, certification scope, partner responsibilities and delivery arrangements must be confirmed in the relevant written agreement. Program scope and potential population reach must not be interpreted as completed rollout or active-user measurements.</p><h2>Regulated services</h2><p>Descriptions of banking or payment functionality concern planned integration with appropriately licensed partners. They do not constitute an offer of an unlicensed financial service or an investment solicitation.</p><h2>Contact</h2><p>For clarification about website information, email info@gentech.ae before relying on it for a commercial decision.</p>'),
'compliance.html':('Compliance & responsible communication','<h2>Clear scope for technical claims</h2><p>Capability descriptions distinguish system design from live deployment. No group-wide payment, security, telecommunications or manufacturing certification is asserted on these pages.</p><h2>Product-specific evidence</h2><p>Certification, where relevant to a selected product, must be checked against the certificate holder, product and service scope, applicable market and validity period. A supplier’s certification is not a certification of Gentech Group.</p><h2>Regulated activities</h2><p>'+e(ARCHITECTURE)+'</p><h2>Production responsibilities</h2><p>The cards platform covers design, customisation, personalisation, production management and supply. Manufacturing arrangements and responsibilities are established for each order; this website does not claim that every product is made in a Gentech-owned facility.</p><h2>Corporate and program roles</h2><p>Corporate roles are described separately from ownership or contractual-signatory status. Questions about supporting documentation can be directed to info@gentech.ae.</p>')}
for file,(title,copy) in legal.items():
    if file == 'privacy.html' and contact_endpoint:
        copy = (TEMPLATES/'contact-privacy.html').read_text()
    page(file,title,title+' for Gentech Group and its international corporate platforms.',intro('CORPORATE INFORMATION',title,'Information scope, corporate details and responsible communication.')+'<section class="g-section"><div class="g-container g-prose">'+copy+'</div></section>')
page('404.html','Page not found','Find the Gentech Group page you are looking for.',intro('404 / PAGE NOT FOUND','Let’s get you connected.','The page may have moved. Explore our business platforms or return to the homepage.')+'<section class="g-section"><div class="g-container">'+link('index.html','Return home','g-button')+platformcards()+'</div></section>')

redirects={'ceramiccards.html':'solutions-cards.html#product-families','chip.html':'solutions-cards.html#product-families','chipmodules.html':'solutions-cards.html#product-families','emvcards.html':'solutions-cards.html#product-families','hardware.html':'solutions-payments.html','metalcards.html':'solutions-cards.html#studio','perso.html':'solutions-cards.html#configurator','products.html':'solutions-cards.html','service.html':'index.html#business-platforms','telecom.html':'solutions-telecom.html','transport.html':'solutions-mobility.html','wearable.html':'solutions-cards.html#studio'}
for old,target in redirects.items():
    (ROOT/old).write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page moved | Gentech Group</title><meta name="robots" content="noindex,follow"><link rel="canonical" href="https://gentech.ae/{target.split("#")[0]}"><meta http-equiv="refresh" content="0;url={target}"></head><body><p>This page has moved. <a href="{target}">Continue to Gentech Group</a>.</p><script>const target = new URL({json.dumps(target)}, location.href); target.search = location.search; location.replace(target.href);</script></body></html>\n')
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://gentech.ae/'+('' if f=='index.html' else f)+'</loc></url>' for f in PAGES if f!='404.html')+'</urlset>\n')
(ROOT/'robots.txt').write_text('User-agent: *\n'+('Allow: /\nSitemap: https://gentech.ae/sitemap.xml\n' if production else 'Disallow: /\n# GitHub preview; production indexing requires an explicit production build.\n'))
print(f'Built {len(PAGES)} pages and {len(redirects)} legacy redirects ({"production" if production else "preview / noindex"}).')
