"""Approved corporate facts and conservative platform copy from the 24-point brief."""
HUBS = [
    dict(key='canada',city='Toronto',country='Canada',name='GENTECH CAPITAL HOLDINGS INC.',address='35 Esterbrooke Avenue, Unit 1114, Toronto, Ontario M2J 2C6, Canada',role='Capital, investment & strategic coordination',description='GENTECH CAPITAL HOLDINGS INC. serves as Gentech Group’s capital, investment and strategic coordination platform.'),
    dict(key='uae',city='Ras Al Khaimah',country='United Arab Emirates',name='GENTECH GLOBAL FZ-LLC',address='VUNE1303, Compass Building - Al Hulaila, Al Hulaila Industrial Zone-FZ, Ras Al Khaimah, United Arab Emirates',role='Technology, integration & international trade',description='GENTECH GLOBAL FZ-LLC is Gentech Group’s technology and international trade platform, coordinating product design, technology integration, production management and international supply.'),
    dict(key='africa',city='Johannesburg',country='South Africa',name='GENTECH CAPITAL HOLDINGS (PTY) LTD',address='18 Melrose Boulevard, Melrose Arch, Melrose North, Gauteng 2196, South Africa',role='Operations & program implementation',description='GENTECH CAPITAL HOLDINGS (PTY) LTD serves as Gentech Group’s Johannesburg-based operating and implementation company for the program.')
]
PLATFORMS = [
    dict(key='capital',title='Capital & Strategic Investments',short='Capital & investments',description='Bringing investment strategy, project structuring and capital coordination together for long-term infrastructure development.',items=['Investment strategy and capital coordination','Project development and financial structuring','International commercial partnerships','Long-term project evaluation'],image=None),
    dict(key='infrastructure',title='Infrastructure Development',short='Infrastructure',description='Developing technology-led infrastructure from feasibility and system design to integration planning and operational readiness.',items=['Project feasibility and delivery planning','Secure Cloud Infrastructure','Data and system integration design','Operational readiness and lifecycle planning'],image=None),
    dict(key='mobility',title='Smart Mobility Systems',short='Smart mobility',description='Connecting transport operators, passenger access and payment technologies through integrated mobility programs.',items=['Fare collection and account-based ticketing design','In-vehicle validators and driver interfaces','Fleet connectivity and operational data','Phased implementation and support planning'],image='mobility_banner.webp'),
    dict(key='payments',title='Payment Technologies',short='Payment technologies',description='Coordinating secure payment products and acceptance architectures with appropriately licensed banking and payment partners.',items=['Payment terminal selection and integration','Contactless and QR acceptance design','Reconciliation and settlement integration planning','Banking and payment partner coordination'],image='pos.webp'),
    dict(key='telecom',title='Telecommunications & Connected Devices',short='Connected devices',description='Connecting devices, vehicles and infrastructure with communications products selected for each market and operating environment.',items=['SIM and eSIM product coordination','Connected terminal and vehicle integration','Fleet data connectivity planning','Device supply and lifecycle support'],image='supersim.webp'),
    dict(key='cards',title='Card Technologies & Manufacturing',short='Card technologies',description='Design, customisation, personalisation, production management and international supply of cards and secure payment products.',items=['Card and wearable product design','Material and finish customisation','Personalisation and production management','International sourcing and supply coordination'],image='metalcard.webp')
]
MODEL = [
    ('Develop','Shape the opportunity.','Define the project, establish its scope and build a delivery model around market and operating needs.'),
    ('Finance','Structure the capital.','Coordinate investment strategy and financing structures that support a project’s long-term development.'),
    ('Integrate','Connect the technology.','Bring hardware, software and specialist partners together around a coherent system architecture.'),
    ('Operate','Build for the long term.','Plan implementation, local support and operating responsibilities throughout the project lifecycle.')
]
POSITION='Gentech Group develops, finances, integrates and operates technology-driven infrastructure across global markets.'
HERO='Building Technology-Driven Infrastructure Across Global Markets'
INTRO='Gentech Group develops, finances, integrates and operates large-scale platforms across digital payments, smart mobility, telecommunications and secure technology infrastructure.'
PROGRAM='A contractually established 10-year national digital transportation and payments program under Gentech’s agreement with SANTACO acting through TaxiChoice.'
ARCHITECTURE='The program architecture is designed to support these capabilities together with appropriately licensed banking, payment and technology partners.'
